version: "3.9"
services:
  website:
    container_name: zus_example_website
    build:
      context: ../
      dockerfile: Dockerfile
      # args:
      #   buildno: 1
    ports:
     - "3008:80"
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 20M
    networks:
      default:

networks:
  default:
    driver: bridge
